FROM openjdk:8u222-jdk-slim-buster

RUN apt update && apt install --no-install-recommends -y curl git locales nodejs npm \ 
	&& curl -fsSLo /var/lib/apt/lists/docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-19.03.1.tgz \
    && tar xzvf /var/lib/apt/lists/docker.tgz --strip=1 -C /usr/bin docker/docker \
    && sed -i 's/# \(en_US\.UTF-8 .*\)/\1/' /etc/locale.gen && locale-gen && update-locale LANG=en_US.UTF-8 \
    && npm install -g yarn